# Generated by Django 4.2.3 on 2023-10-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
